version: '3.8'

services:
  web:
    build:
      context: app
    ports:
      - "8081:5000"
    env_file:
      - .env.dev
    networks:
      - dev_network
  mydb:
    image: mysql:8.0
    env_file:
      - .env.dev
    volumes:
      - db_data_dev:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - dev_network
  myadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mydb
      PMA_SESSION: PMA_SESSION_DEV
    ports:
      - "9081:80"
    depends_on:
      - mydb
    networks:
      - dev_network

volumes:
  db_data_dev:
    name: db_data_dev

networks:
  dev_network:
    name: dev_network
    driver: bridge