version: '3.8'

services:
  test_web:
    build:
      context: app
    ports:
      - "8082:5000"
    env_file:
      - .env.test
    networks:
      - test_network

  test_mydb:
    image: mysql:8.0
    env_file:
      - .env.test
    volumes:
      - db_data_test:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - test_network

  test_myadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: test_mydb
      PMA_SESSION: PMA_SESSION_TEST
    ports:
      - "9082:80"
    depends_on:
      - test_mydb
    networks:
      - test_network

volumes:
  db_data_test:
    name: db_data_test

networks:
  test_network:
    name: test_network
    driver: bridge